[package]
name = "pico"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.10"
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4"
sdl2 = { version = "0.38", features = ["bundled"] }
