[package]
name = "pico"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.10.0"
clap = { version = "4.5.51", features = ["derive"] }
crossterm = "0.29.0"
rand = "0.9.2"
sdl2 = { version = "0.38.0", features = ["bundled"] }
